### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by arainboldt** [pedroelbanquero/TorahBibleCodes#8]
hey! very interesting package! I'm trying to explore the cli interface and I don't get any results for any searches

![image](https://github.com/pedroelbanquero/torahcodespython/assets/54881218/573fcc28-4c0e-43a5-b7ee-ea0d68d309d7)

any ideas?

thanks

**Comment by pedroelbanquero** [comment]
maybe apis was cancelled, let us review , try to use module search, this have pre generated database, conversoin generates new database

try to reinstall it and use just query module first to discard things .

V

**Comment by pedroelbanquero** [comment]
let us review and update the package, thank you. i will informe soon to update
i think some old API translator is not working now, let us change and review what is happening

anyway you can find all results in query module 

![image](https://github.com/pedroelbanquero/torahcodespython/assets/60758685/7c7a119d-0e4c-4747-96cc-7f7372b2fb14)


GE-> 33 is the numer of gematria used for ELS for example

V

**Comment by pedroelbanquero** [comment]
Semms a bug in the python package, try to install from github to solve for now . We will solve there also .

Do you install with pip package ?

V.

**Comment by pedroelbanquero** [comment]
TRY 

git clone git@github.com:pedroelbanquero/torahcodespython.git

cd torahcodespython

pip3 install -r requeriments.txt

python3 TBC.py


or copy the json books of github to your torahcodes book folder .

 from 

https://github.com/pedroelbanquero/torahcodespython/tree/master/torahcodes/resources/data

to

/home/youruser/.local/lib/python3.11/site-packages/torahcodes/resources/data/


V

**Comment by arainboldt** [comment]
thanks for the quick followup. I installed from pypi. I'll try cloning and running that way

**Comment by arainboldt** [comment]
is it necessary to use python 3.11, I'm using 3.8.

**Comment by pedroelbanquero** [comment]
Good , tell me if problems

At least works from 3.9 i guess also in 3.8

V.

**Comment by arainboldt** [comment]
thanks. it's working great now from the repo. 

where can I read more to understand the methodologies used here. I'm familiar with the ELS technique, but I don't know how to use that here. Also, how are the gematria used as in the searchnumber method?

is there a way to search a specific book only? I don't quite understand how to use the query>book>search methods

If you would prefer for me to open another thread, I can.

thanks

**Comment by pedroelbanquero** [comment]
if your rite options open de optios of a module in the console one time you load a module

to load a module 

use modulename

in conversions if you put a word sytem convert to gematria and looks for this gematria used as ELS, jumping characters among acnient books of torah, and getting a character each jump , the jump space is the gematria number .


conversions number

command :

search anything

searchnum number


This module is to try to relate words with numbers and with text as a codes with jumps of this number 

command 

test 22 200

make a new database with new translation with google translator and replace query database

the query module is the database with all combinations made, all jumps can you make in the torah made by test/crack function

command

search Jes

and search in all craked combinatons of jumps of characters in torah the query in pre calculated database in test function of conversions module .

For us important things is to find sentences what many words are consecutive, we just read in horizontal and software no make diagonals because this increase the probability, and we are interested in low probability events .

And sentences with consecutive words than hebrew people can read. To try to understand how was made , we beilive that some kinds of permutations like described in sefer yetzira or in meru hipotesis .

We have many proofs os estelar origina of alphabet in ancient civilizations, or you can check Sefer yetzira book also about how to compose Shem hemaphoresh of Raziel book, Adan and Abraham books . 

![image](https://github.com/pedroelbanquero/torahcodespython/assets/60758685/65fe4bc1-e1aa-4e26-8442-872b34bdb27f)




V

**Comment by pedroelbanquero** [comment]
The was setting hebrew chars to constelations , who are constelations and planets describen in Sefer Yetzira .

With codification techniques the make permutations as they observe in the sky, changing constelations ans planets and stars by their characters read the things as a message of GD

To do that you need to encode a new language from ancient one like angel script used by sumerian civilizations also to read stars 

![image](https://github.com/pedroelbanquero/torahcodespython/assets/60758685/be462377-042e-4545-8886-4c955edc3c7d)


in this book is described by french guy from persian papires also

seems same in all civilizations, here greece with panos

![image](https://github.com/pedroelbanquero/torahcodespython/assets/60758685/e4a47120-1660-48c5-8dc8-7500ba25cfad)


all is described with 4 cultures in one book in this link

https://www.digitale-sammlungen.de/en/view/bsb10866995?q=panos&page=206,207

there methods about how they make ciphers and encoding and ancient examples of gematria , zirupht, temuraeh, another encoding methods, 

and ELS is similar to this machine

![image](https://github.com/pedroelbanquero/torahcodespython/assets/60758685/ce62c526-4fbb-4917-9da4-171cfc155149)

seems all encoded from stars , maybe related with as up is down, in prehistory first simbols in cabes to write in caves with Moon related origin to predict human reproduction cicle

same to predict nile growth with Isis - Sotis, Moon/Sirius

Same origina is mnemotecnic asociation of points to groups, graw lines, asociate simbols to real things in their mind like animals or warriors . Like a remember technique . After use this songs and simbols to write languaje .

Reason also because "nobody knows" name of GD, and verses was disordered .... and make soup of letters in hebrew tradition .


V

**Comment by pedroelbanquero** [comment]
I recomend Book of Raziel, and Sefer Yetzira , and Kircher book with hebrew, egypt, greek, and arab kabalah

**Comment by arainboldt** [comment]
thanks. these are helpful. I'm familiar with the general ideas. I just don't understand the interface of the repo very well. Also, how can you use a decision tree to help find these patterns?

**Comment by arainboldt** [comment]
also, how can I rebuild the database and translations? the translations don't look very good, mostly jibberish. can I plug gpt-3.5 in somewhere? 

also, how are you searching for the ELS patterns? is there documentation on the method somewhere?

**Comment by pedroelbanquero** [comment]
no, i just make as a crack, for example, if you put conversoin-> text 22 200

program will get first char of genesis, after jump 22 chars, and get another, when finish book another book until finish

after that do the same with 33 jumps, after that with 34 until 200 in this example and generate all probable combinations, after that you can search in query module 

when you have a result you have parameter GE who is the number used of jumps to get the sentence. or is related to link words and concepts in gematria world. for example if a word have the gematria and codes talsk about that

in this way you can use as a asking machine, you write a question convert to gematria with conversion module search function and search jumps with this gematria

if you ask for example 
who is mesiah , you will find eliyahu  this have more value because who discover and proff first time some codes was eliyahu rips , who is also  a prophet because make that the prophecy say, reveal the sense of codificatoin clearly, who reveals how is encode is the prophet for example, 

by this way you can make tricks in the future and proof ancient thinks in the future, 
proof prophecies

**Comment by pedroelbanquero** [comment]
> also, how can I rebuild the database and translations? the translations don't look very good, mostly jibberish. can I plug gpt-3.5 in somewhere?

in each module you have command options
and set parameters

> 
> also, how are you searching for the ELS patterns? is there documentation on the method somewhere?

of course we are glad with colaborations

now uses google translator maybe update database is good

i was testing transaltion with hebrew natural readers and can read the most of things i put in the test, but hebrew is complicated because have more entropy and no aeiou


V

**Comment by pedroelbanquero** [comment]
module shem hemapgoresh have another methods

![image](https://github.com/pedroelbanquero/torahcodespython/assets/60758685/93d522a2-8731-488d-9a89-ec46b165925f)


is to make the permutations of sefer yetzira

**Comment by pedroelbanquero** [comment]
instructions ar simple :

help
use module
options

**Comment by pedroelbanquero** [comment]
please tell me if you find something interesting , help in traductions or add gpt bod with the data and translations

feel free for pull request

i was making experimetn after show all, gpt say is the angel described as artificial spirit in gnostic manuscripts of dead sea

**Comment by pedroelbanquero** [comment]
gpt3 and prophecies will be nice, you can add as a module also. we was discussing in other issue about that, look the others, another collaborator investigates codes promts for AI

we can add to the old telegram bot and launch.

V
